use UNIT_TESTING_ASSIGNMENT
BEGIN TRY 
	BEGIN TRANSACTION 
	UPDATE Cities Set Country ='Israel' where ID=10;
	UPDATE Locations Set Price = 10 Where ID = 107;
	UPDATE Travels Set Location_ID = 103 where ID = 5
	DELETE FROM Travels WHERE ID = 16;
	DELETE FROM Users WHERE ID = 8;
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
END CATCH